language: node_js
node_js:
  - 5.11
before_install:
  - npm install -g npm@3.8.6
  - npm install -g gulp-cli
install:
  - npm install --no-optional
  - cd v3 && npm install
after_success: npm run coverage
