language: node_js
dist: trusty
sudo: false
cache:
  yarn: true
  directories:
    - api/node_modules
    - www/node_modules
    - packages/nusmoderator/node_modules
script:
  - yarn install
  - yarn lint
  - yarn test -ci
after_success:
  cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
