---
- command: bower install chdir={{ project_dir }}
- command: bundle install chdir={{ project_dir }}
- composer: working_dir={{ project_dir }}
- npm: path={{ project_dir }}
- npm: path={{ project_dir }}/api
- template:
    src=yourls/user/config.php.j2
    dest={{ project_dir }}/app/vendor/yourls/yourls/user/config.php
